name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          # GStreamer dihapus agar tidak bentrok, ditambahkan libffi-dev untuk kestabilan Python
          sudo apt install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libffi-dev
          pip install --upgrade pip
          pip install --user --upgrade buildozer Cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          rm -rf .buildozer
          buildozer -v android debug --warn-allow-root
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Terminal-Survivor-APK
          path: bin/*.apk
